@startuml
autonumber

actor Receptionist as R
participant ":System" as S

activate R
R -> S: wants to register a test
activate S
S --> R: requests data (ClientTin, NhsNumber)
deactivate S
R -> S: types the requested data
activate S
S --> R: Show TestType list and asks to choose one
deactivate S
R -> S: Choose one TestType
activate S
loop "More categories"
S --> R: shows the list of categories and asks to select
deactivate S
R -> S: selects category
activate S
loop "More parameters"
S --> R: shows the list of parameters and asks to select
deactivate S
R -> S: selects parameter
activate S
end
end
S --> R: confirms all data and asks to confirm
deactivate S
R -> S: confirms data
activate S
S --> R: informs operation success
deactivate S
deactivate R
@enduml