@startuml
autonumber
actor Client as C
participant "ImportTestUI" as UI
participant ":ImportTestController" as CTRL
participant ":ImportTests" as Imp
participant ":Company" as company
participant "clastore:ClinicalAnalysisLabStore" as clastore
participant "cstore:ClientStore" as cstore
participant "tstore:TestStore" as tstore
participant "pcstore:ParameterCategoryStore" as pcstore
participant "pstore:ParameterStore" as pstore
participant "cla:ClinicalAnalysisLab" as cla
participant "ttstore:TestTypeStore" as ttstore
participant "tt:TestType" as tt
participant "c:Client" as c
participant "t:Test" as t
participant "p:Parameter" as p
participant "pc:ParameterCategory" as pc
participant ":AuthFacade" as Auth
participant ":Email" as Email
participant ":UserStore" as ustore
participant "u:User" as u





activate C
C -> UI: wants to import clinical tests
activate UI
deactivate CTRL
UI --> C: show the list of files
deactivate UI

C -> UI: choose the file
activate UI
activate CTRL
UI --> CTRL :readTestFromCSV



activate Imp
CTRL --> Imp: createClientfromFile(metadata)

activate company
Imp --> company: createClient()
company --> cstore: createClient()
deactivate company
activate cstore
cstore -> c** : c = Client(phoneNumber, cc, nhs, tinNumber, birthDate, email, name)
cstore -> cstore: saveClient()
activate company
Imp --> company: addUserWithRole()
company --> Auth: addUserWithRole()
deactivate company
deactivate cstore
activate Auth
Auth -> ustore:create()
deactivate Auth
activate ustore
ustore -> u**: u = User(id, password, name, role)
deactivate ustore
Imp --> Email: sendPasswordNotification()
activate Email
deactivate Email




Imp --> company: verifyClinicalLabID()
activate company
company --> clastore: verifyClinicalLabID()
deactivate company
activate clastore
activate cla
clastore -> cla: getId()
deactivate clastore
deactivate cla



Imp --> company: getTestTypeExist()
activate company
company --> ttstore: getTestTypeExist()
deactivate company
activate ttstore
ttstore -> tt : getDescription()
activate tt
deactivate ttstore
deactivate tt







activate pcstore

activate company

Imp --> company: getParameterCategoryExist()
company --> pcstore: getParameterCategoryExist()
deactivate company

deactivate pcstore
deactivate company



Imp --> company: getParameterExist()
activate company
company --> pstore: getParameterExist()

activate pstore

deactivate company
deactivate pstore

Imp --> company: createTest()

activate company
company --> tstore: createTest()
deactivate company
activate tstore
tstore -> t**: t = Test(testNhsNumber, clientTin, testType, catList, paList)
tstore -> tstore: saveTest()
ref over Imp: addTestResult(parameterCode,result)


Imp --> t:changeState()
deactivate tstore
activate t

CTRL --> Imp: getTestFileList()
deactivate t


UI --> CTRL :saveFileTestList()


deactivate CTRL


UI --> C: shows the tests that were imported
deactivate UI





deactivate UI
deactivate C
@enduml