@startuml
autonumber
actor "Clinical Chemistry Technologist" as cct
participant ":RecordResultsUI" as UI
participant ":RecordResultsController" as ctrl
participant ":Test" as Test

activate cct
cct -> UI: Asks for record the results of a given test
activate UI
UI --> cct: Asks for the code of the sample
deactivate UI
cct -> UI: Inserts the sample ID
activate UI
UI -> ctrl: SD_getTestParameterList(sampleId)
ref over ctrl: SD_AddTestResult(parameterCode,result,metric)
activate ctrl
ctrl --> UI: tpStoreDTO
deactivate ctrl
loop for all the parameters
    UI --> cct: Show parameters and asks to choose one
    deactivate UI
    cct -> UI: Choose parameter
    activate UI
    UI -> cct: Asks for results value
    deactivate UI
    cct -> UI: Types results value
    activate UI

    UI -> ctrl: addTestResult(parameterCode,result)
    activate ctrl
    ctrl -> Test: addTestResult(parameterCode,result)
    activate Test
    ref over Test : SD_AddTestResult(parameterCode,result)
    Test --> ctrl : ok
    deactivate Test

end
ctrl -> Test: ChangeStage()
activate Test
Test -> Test: changeState()
activate Test
deactivate
Test --> ctrl: ok
deactivate
ctrl --> UI : ok
deactivate ctrl


UI --> cct: Show all data and show success
deactivate UI




@enduml