@startuml
'https://plantuml.com/class-diagram

hide methods
skinparam classAttributeIconSize 0

class User{
-Name
-Email
-Password
}

class Employee{
-Employee ID;
-Name;
-Address;
-Phone Number;
-E-Mail;
-Standard Occupational Classification "SOC";
}

class SpecialistDoctor{
-Doctor Index Number;
}

class OrganizationRole{
-Description
}

class Company{
-Name
}
Company "1" - "*" OrganizationRole: knowns all the >
Employee "1" - "1" OrganizationRole: is characterized by a  >
Employee "1" -- "1" User: is a >
Company "1" -- "*" Employee: employs >
Administrator"1" -- "1" Employee: is a >

Employee "1" -- "1" SpecialistDoctor: can be a >
Administrator "1" -- "1" Employee: register >

@enduml