@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Administrator" as ADM
participant ":System" as SYS
activate ADM

ADM -> SYS : asks to create a new employee
activate SYS
SYS --> ADM: asks for authentication data
deactivate SYS

ADM -> SYS: input the login data (email; password)
activate SYS
ADM <-- SYS: asks which type of employee
deactivate SYS

ADM -> SYS: choose type of employee
activate SYS
ADM <-- SYS: asks for employee data(Name,Address,\n Phone Number, E-Mail, "SOC", Doctor Index Number)
deactivate SYS

ADM -> SYS: type employee data
activate SYS
ADM <-- SYS: Shows data and requests confirmation
deactivate SYS

ADM -> SYS: confirms data
activate SYS
ADM <-- SYS: shows operation success
deactivate SYS

@enduml