@startuml
'https://plantuml.com/class-diagram

class CreateParameterCategoryUI{
}
class CreateParameterCategoryController{
-company
- parameterStore
+saveParameterCategory()
+createParameterCategory(code, name)
}
class Company{
-parameterStore
-designation
+getParameterCategoryStore()
}
class ParameterCategoryStore{
-categoryList
-category
+createParameterCategory(code, name)
+saveParameterCategory(pc)
+validateParameterCategory(pc)
+addParameterCategory(pc)
}

class ParameterCategory{
-code
-name
+ParameterCategory(code,name)
}
CreateParameterCategoryUI --> CreateParameterCategoryController
CreateParameterCategoryController --> Company
CreateParameterCategoryController ..> ParameterCategoryStore
Company -->  ParameterCategoryStore
ParameterCategoryStore "1" --> "*" ParameterCategory

@enduml