@startuml
autonumber
'hide footbox
actor "Administrator" as Administrator

participant ":CreateParameterUI" as UI
participant ":CreateParameterController" as CTRL
participant ":Company" as COMPANY
participant "pStore : ParameterStore" as PARAMETERSTORE
participant ":ParameterCategoryStore" as CATEGORYSTORE
participant "pa : Parameter" as PARAMETER


activate Administrator
Administrator -> UI: asks to create a new Parameter
activate UI




UI --> Administrator :requests ParameterData (code, description, NHSid)
deactivate UI


Administrator -> UI : types requested data
activate UI

activate CTRL


UI -> CTRL : getCategoryList()


CTRL -> COMPANY : catList = getCategoryList()
activate COMPANY




COMPANY -> CATEGORYSTORE  : catList = getCategoryList()

activate CATEGORYSTORE
deactivate CATEGORYSTORE
deactivate COMPANY





UI --> Administrator : Show Category list and ask to select one





Administrator -> UI : selects a parameter category

CTRL -> COMPANY : pStore = getParameterStore
activate COMPANY
deactivate COMPANY

UI-> CTRL : createParameter()
CTRL -> PARAMETERSTORE : pa = createParameter(code, description, NHSid, Category)

activate PARAMETERSTORE

PARAMETERSTORE -> PARAMETER : pa = createParameter(code, description, NHSid, Category)

activate PARAMETER
deactivate PARAMETER
deactivate PARAMETERSTORE
CTRL -> PARAMETERSTORE : validateParameter(pa)
activate PARAMETERSTORE
deactivate PARAMETERSTORE

UI --> Administrator : shows all data and requests confirmation

Administrator -> UI : confirms the data

UI-> CTRL : saveParameter()

CTRL -> PARAMETERSTORE : saveParameter(pa)
activate PARAMETERSTORE
PARAMETERSTORE -> PARAMETERSTORE : validateParameter(pa)
PARAMETERSTORE -> PARAMETERSTORE : saveParameter(pa)


UI --> Administrator : Informs operation success
deactivate PARAMETERSTORE







@enduml