@startuml

class ParameterCategory {
  -String CategoryName
  -String Code
}

class Company{
+getCategoryList()
+getParameterStore()
}

class CreateParameterController {
+createParameter(code, description, NHSid, Category)
+getCategoryList()
+saveParameter()
}

class CreateParameterUI{
}

class ParameterCategoryStore{
+getCategoryList()
}

class ParameterStore{
+createParameter()
+validateParameter()
+saveParameter()
}

class Parameter{
-code: String
-name: String
-description: String
-Cat: Category
+Parameter()
}

CreateParameterUI ..> CreateParameterController

CreateParameterController ..> Company
CreateParameterController ..> ParameterStore

Company --> ParameterCategoryStore
Company --> ParameterStore

ParameterStore --> Parameter

ParameterCategoryStore --> ParameterCategory

Company --> Parameter
Company --> ParameterCategory
Parameter  -->  ParameterCategory
@enduml