@startuml
'https://plantuml.com/class-diagram

class ChemicalAnalysis{
}
class Test{
Client;
Test ID;
Type of Test;
}
class Sample{
Test ID;
Type of Sample;
}
class Covid19Tests{
Covid19 Value;
}
class AnalysisOfBlood{
Number Red Blood Cells;
Number White Blood Cells;
Number Platelets;
}
class Client{
Name;
Citizen card Number;
National Healthcare Service Number
Birth date;
Sex;
Tax Identification Number;
Phone;
E-mail;
}
class Receptionist{
Employee ID;
Organization Role;
Name;
Address;
Phone Number;
E-Mail;
Standard Occupational Classification "SOC";
}
class MedicalLabTechnician{
Employee ID;
Organization Role;
Name;
Address;
Phone Number;
E-Mail;
Standard Occupational Classification "SOC";
}
class SpecialistDoctor{
Employee ID;
Organization Role;
Name;
Address;
Phone Number;
E-Mail;
Standard Occupational Classification "SOC";
Doctor Index Number;
}
class Administrator{
Employee ID;
Organization Role;
Name;
Address;
Phone Number;
E-Mail;
Standard Occupational Classification "SOC";
}
class ClinicalChemistryTechnologist{
Employee ID;
Organization Role;
Name;
Address;
Phone Number;
E-Mail;
Standard Occupational Classification "SOC";
}
class LaboratoryCoordinator{
Employee ID;
Organization Role;
Name;
Address;
Phone Number;
E-Mail;
Standard Occupational Classification "SOC";
}
class ClinicalAnalysisLaboratory{
Laboratory ID;
Name;
Address;
Phone Number;
TIN number;
}
class ChemicalLaboratory{
Name;
Address;
Phone Number;
TIN number;
}
class CompanyHeadquarters{
Employee ID;
Organization Role;
Name;
Address;
Phone Number;
E-Mail;
Standard Occupational Classification "SOC";
}
class ChemicalAnalysis{
}
class BloodSample{
}
class SwabSample{
}
class ManyLabs{
}
class BarcodeExternalAPI{
Barcode Number;
}
class LabOrder{
}
class Results{

}
class Report{
}


ManyLabs "1" -- "*" ClinicalAnalysisLaboratory: owns >
ManyLabs "1" -- "1" ChemicalLaboratory: owns >
ManyLabs "1" -- "1" CompanyHeadquarters: owns >
ManyLabs "1" -- "*" Receptionist: employs  >
ManyLabs "1" -- "*" MedicalLabTechnician: employs >
ManyLabs "1" -- "*" SpecialistDoctor: employs >
ManyLabs "1" -- "*" Administrator: employs >
ManyLabs "1" -- "*" ClinicalChemistryTechnologist: employs >
ManyLabs "1" -- "*" LaboratoryCoordinator: employs >
Client "1" -- "1" LabOrder: to execute the test needs a  >
BloodSample "1" -- "1" Sample: is a type of >
SwabSample "1" -- "1" Sample: is a type of >
ChemicalLaboratory "1" -- "1" CompanyHeadquarters: is located in >
Receptionist "*" -- "1" ClinicalAnalysisLaboratory: works on >
Receptionist "1" -- "*" Test: register in application >
Receptionist "1" -- "*" Client: register in application >
MedicalLabTechnician "1" -- "*" Sample: collects and records >
SpecialistDoctor "1" -- "1" Report: writes >
SpecialistDoctor "1" -- "1" Results: analyse >
Sample "*" -- "1" ChemicalLaboratory: are sent >
ClinicalChemistryTechnologist "1" -- "1" Sample : analyse >
ClinicalChemistryTechnologist "1" -- "1" Results : records >
ClinicalChemistryTechnologist "*" -- "1" ChemicalLaboratory : works on >
AnalysisOfBlood "*" -- "*" Test : is a type of >
Covid19Tests "*" -- "*" Test : is a type of >
Sample "1" -- "1" Test : is used in >
Report "1" -- "1" Client : is delivered to >
ChemicalAnalysis "*" -- "1" ChemicalLaboratory : take place in >
Sample "1" -- BarcodeExternalAPI : is identified using >

@enduml