@startuml
'https://plantuml.com/class-diagram

class ChemicalAnalysis{
}
class Test{
}
class Sample{
}
class Covid19Tests{
}
class AnalysisOfBlood{
}
class Client{
}
class Receptionist{
}
class MedicalLabTechnician{
}
class SpecialistDoctor{
}
class Administrator{
}
class ClinicalChemistryTechnologist{
}
class LaboratoryCoordinator{
}
class ClinicalAnalysisLaboratory{
}
class ChemicalLaboratory{
}
class CompanyHeadquarters{
}
class ChemicalAnalysis{
}
class BloodSample{
}
class SwabSample{
}
class ManyLabs{
}
class BarcodeExternalAPI{
}
class LabOrder{
}
class Results{
}
class Report{
}


ManyLabs "1" -- "*" ClinicalAnalysisLaboratory: owns >
ManyLabs "1" -- "1" ChemicalLaboratory: owns >
ManyLabs "1" -- "1" CompanyHeadquarters: owns >
ManyLabs "1" -- "*" Receptionist: employs  >
ManyLabs "1" -- "*" MedicalLabTechnician: employs >
ManyLabs "1" -- "*" SpecialistDoctor: employs >
ManyLabs "1" -- "*" Administrator: employs >
ManyLabs "1" -- "*" ClinicalChemistryTechnologist: employs >
ManyLabs "1" -- "*" LaboratoryCoordinator: employs >
Client "1" -- "1" LabOrder: to execute the test needs a  >
BloodSample "1" -- "1" Sample: is a type of >
SwabSample "1" -- "1" Sample: is a type of >
ChemicalLaboratory "1" -- "1" CompanyHeadquarters: is located in >
Receptionist "*" -- "1" ClinicalAnalysisLaboratory: works on >
Receptionist "1" -- "*" Test: register in application >
Receptionist "1" -- "*" Client: register in application >
MedicalLabTechnician "1" -- "*" Sample: collects and records >
SpecialistDoctor "1" -- "1" Report: writes >
SpecialistDoctor "1" -- "1" Results: analyse >
Sample "*" -- "1" ChemicalLaboratory: are sent >
ClinicalChemistryTechnologist "1" -- "1" Sample : analyse >
ClinicalChemistryTechnologist "1" -- "1" Results : records >
ClinicalChemistryTechnologist "*" -- "1" ChemicalLaboratory : works on >
AnalysisOfBlood "*" -- "*" Test : is a type of >
Covid19Tests "*" -- "*" Test : is a type of >
Sample "1" -- "1" Test : is used in >
Report "1" -- "1" Client : is delivered to >
ChemicalAnalysis "*" -- "1" ChemicalLaboratory : take place in >
Sample "1" -- BarcodeExternalAPI : is identified using >

@enduml