@startuml
'https://plantuml.com/sequence-diagram
autonumber
actor "Laboratory Coordinator" as lc
actor "System" as SYS
activate lc
lc -> SYS: Asks the list of tests waiting to validation
activate SYS
SYS --> lc: Shows all the tests pending validation and asks to choose one
deactivate SYS
lc -> SYS: Chose the test that will be validated
activate SYS
SYS --> lc: Shows the test results and the report and asks for validation
deactivate SYS
lc -> SYS : Validates both
activate SYS
SYS --> lc: Shows success
deactivate lc

@enduml