@startuml
autonumber
actor Administrator as A
participant "System" as S
activate A
activate S
A -> S: wants to register a new clinical analysis laboratory
loop
S --> A: shows types of test list
deactivate S
A -> S: selects types of tests
activate S
end
S --> A: requests data (laboratory ID, name, address,\n phone number, TIN number)
deactivate S
A -> S: types requested data
activate S
S --> A: shows all data and requests confirmation
deactivate S
A -> S: confirms the data
activate S
S --> A: informs operation success
deactivate S
deactivate A
@enduml