@startuml
'https://plantuml.com/sequence-diagram
autonumber
actor Administrator as A
participant ":CreateClinicalAnalysisLabUI" as UI
participant ":CreateClinicalAnalysisLabController" as CTRL
participant ":Company" as C
participant "cal: Clinical Analysis Laboratory" as CAL
activate A

A -> UI: wants to register a new clinical analysis laboratory
activate UI
UI --> A: requests data (labID, name, address,\n phoneNumber, tinNumber)
deactivate UI
A -> UI: types requested data
activate UI
activate CTRL
UI -> CTRL : CreateClinicalAnalysisLab(labID, name, address, phoneNumber, tinNumber)
CTRL -> C: cal = CreateClinicalAnalysisLab(labID, name, address, phoneNumber, tinNumber)
activate C
C --> CAL : create(labID, name, address, phoneNumber, tinNumber)
activate CAL
deactivate CAL
deactivate C
CTRL -> C: validateClinicalAnalysisLab(cal)
activate C
UI --> A: shows types of test list and asks to select types
deactivate C
deactivate CTRL
deactivate UI
A -> UI: selects types of tests
activate UI
UI -> CTRL: setData(TypesTest)
activate CTRL
CTRL -> CAL: setTypeTest(cal)
activate CAL
deactivate CAL
deactivate C
CTRL -> C: validateClinicalAnalysisLab(cal)
activate C
C -> CAL : validate()
activate CAL
deactivate CAL
deactivate C
UI --> A: shows all data and requests confirmation
deactivate CTRL
deactivate UI
A -> UI: confirms the data
activate UI
UI-> CTRL : saveClinicalAnalysisLab()
activate CTRL
CTRL -> C: saveClinicalAnalysisLab(cal)
activate C
C -> C : validateClinicalAnalysisLab(cal)
activate C
deactivate C
C -> C : saveClinicalAnalysisLac(cal)
activate C
deactivate C
deactivate C
UI --> A : Informs operation success
deactivate CTRL
deactivate UI
deactivate A
@enduml