@startuml

class Company
{
  -designation
  +CreateClinicalAnalysisLab(labID, name, address, phoneNumber, tinNumber)
  +validateClinicalAnalysisLab(cal)
  +saveClinicalAnalysisLab(cal)
}

class CreateClinicalAnalysisLabUI {
}

class CreateClinicalAnalysisLabController {
    +CreateClinicalAnalysisLab(labID, name, address, phoneNumber, tinNumber)
    +setData(TypesTest)
    +saveClinicalAnalysisLab()
}

class ClinicalAnalysisLaboratory{
    -labID
    -name
    -address
    -phoneNumber
    -tinNumber
    +create(labID, name, address, phoneNumber, tinNumber)
    +setTypeTest(cal)
    +validate()
}

CreateClinicalAnalysisLabUI ..> CreateClinicalAnalysisLabController
CreateClinicalAnalysisLabController ..> Company
CreateClinicalAnalysisLabController ..> ClinicalAnalysisLaboratory
Company ..> ClinicalAnalysisLaboratory: creates

@enduml