@startuml

class Company
{
  -designation
  +CreateClinicalAnalysisLab(int labID, string name, string address, int phoneNumber, int tinNumber)
  +validateClinicalAnalysisLab()
  +saveClinicalAnalysisLab()
}

class CreateClinicalAnalysisLabUI {
}

class CreateClinicalAnalysisLabController {
    +CreateClinicalAnalysisLab(int labID, string name, string address, int phoneNumber, int tinNumber)
    +setData(TypesTest)
    +saveClinicalAnalysisLab()
}

class ClinicalAnalysisLaboratory{
    -labID
    -name
    -address
    -phoneNumber
    -tinNumber
    +create(int labID, string name, string address, int phoneNumber, int tinNumber)
    +setTypeTest()
    +validate()
}

CreateClinicalAnalysisLabUI ..> CreateClinicalAnalysisLabController
CreateClinicalAnalysisLabController ..> Company
CreateClinicalAnalysisLabController ..> ClinicalAnalysisLaboratory
Company ..> ClinicalAnalysisLaboratory: creates

@enduml