@startuml

class CreateTestTypeUI{
}

class CreateTestTypeController{
    + CreateTestType(testID, collectingMethod, description, catStore)
    + getParameterCategoryStore()
    + saveTestType()
    + add(catStore)
}

class Company{
-designation
    + createParameterCategoryStore()
    + createTestTypeStore()
}

class TestTypeStore{
    + CreateTestType(testID, collectingMethod, description, catStore)
    + ValidateTestType(t)
    + saveTestType(t)
}

class TestType{
-String testeID
-String collectingMethod
-String description
-ParameterCategoryStore catStore
    + TestType(testID, collectingMethod, description, catStore)
}

class ParameterCategoryStore{
    + getParameterCategoryStore()
}

CreateTestTypeUI ..> CreateTestTypeController
CreateTestTypeController ..> Company
Company ..> TestTypeStore
Company ..> ParameterCategoryStore
CreateTestTypeController ..> TestTypeStore
CreateTestTypeController ..> ParameterCategoryStore
TestTypeStore "1" --> "*" TestType: contains
TestType "1"-right-> "1" ParameterCategoryStore: categorized by
@enduml

