@startuml

class Test{
Test code
Nhs Number
Client Tin
Test Type
Categories
Parameters
State
Date
Result
}


class Client{
Name
Citizen Card Number
National Healthcare Service Number
Birth date
Sex
Tax Identification Number
Phone
E-mail

}

class Company{

}



Company "1" -- "*" Test : does >
Company "1"---"*" Client : can reach the information >
Client "1"---"*" Test :  wants to view the results >
@enduml