@startuml
hide methods
left to right direction
skinparam classAttributeIconSize 0


class SpecialistDoctor {

}
class Report{
TestID
Client
Doctor's text
}

class Test{
TestID
}

class Results{
TestID
Client
}

SpecialistDoctor -- Results: analyse >
SpecialistDoctor -- Report: write >
Results -- Test
Report -- Test





@enduml