@startuml
autonumber
actor MedLabTech as MLT
participant ":MedLabTechUI" as UI
participant ":MedLabTechController" as CTRL
participant "ts:TestStore" as TT
participant "store: SampleStore" as STO
participant "s: Sample" as S

activate MLT
MLT -> UI: wants to record the samples
activate UI
UI -> CTRL : SD_getTestList(testID)
ref over CTRL: SD_TestIDDTO(testID)
activate CTRL
CTRL --> UI: tpStoreDTO
deactivate CTRL
loop
UI --> MLT: shows test list
deactivate UI
MLT -> UI: selects a test from the list
activate UI
loop
UI --> MLT: asks for a sample
UI -> CTRL: saveSample()
activate CTRL
CTRL -> STO: saveSample()
deactivate CTRL
activate STO
STO -> S**: saveSample()
deactivate STO
UI --> MLT: shows all data and requests confirmation
deactivate UI
end
end
deactivate UI
deactivate STO
deactivate CTRL
deactivate CTRL
MLT -> UI: confirms the data
activate UI
UI -> CTRL: saveSample()
activate CTRL
CTRL -> STO: saveSample()
activate STO
STO -> STO: validateSample()
STO -> STO: saveSample()
UI --> MLT: informs operation success
deactivate STO
deactivate CTRL
deactivate UI
deactivate MLT
@enduml