@startuml

class RecordSampleUI{
}

class RecordSampleController{
getTestList();
saveSample()
}

class TestStore{
getTestList();
}

class SampleStore{
saveSample();
validateSample();
}

class Sample{
saveSample();
}

RecordSampleUI ..> RecordSampleController
RecordSampleController ..> TestStore
RecordSampleController ..> SampleStore
SampleStore --> Sample

@enduml