@startuml

autonumber
actor Client as C
participant ":System" as S
activate C
C -> S: wants to view the results of a test
activate S
S --> C: shows test list associated to the client
deactivate S
C -> S: selects a test from the list
activate S
S --> C: show the results
deactivate S

deactivate C
@enduml