@startuml
autonumber
actor Client as C
participant ":ViewResultsUI" as UI
participant ":ViewResultsController" as CTRL
participant ":Company" as company
participant ":UserSession" as US
participant ":User" as U
participant "ts:TestStore" as tt
participant "test:Test" as t
participant "cs:ClientStore" as cc
participant "client:Client" as c



activate C
C -> UI: wants to view the results of a test

activate UI
UI -> CTRL :sortedList()
activate CTRL

activate company



CTRL -> company: getUserID()
deactivate c
company -> US: getUserId()
activate US
US -> U: getId()
activate U
deactivate U
deactivate US
deactivate company
CTRL -> cc: getClientByEmail()

activate cc
cc -> c: getTinNumber()
deactivate cc

activate c

CTRL -> tt: sortedDateList(clientTin)
deactivate c

activate tt



deactivate CTRL
UI -> C: show the test list associated with the client
deactivate tt


deactivate UI

C -> UI: select a test from the list
activate UI
UI -> CTRL: getResults()
activate CTRL
CTRL -> t: getResults()
deactivate CTRL
activate t
deactivate t

UI -> C: show the results
deactivate UI





deactivate UI
deactivate C
@enduml