@startuml
'https://plantuml.com/class-diagram

class ClientStore{
-array
-client
+existClient(clientTin)
}
class TestStore{
- array
- test
+createTest(testNhsNumber,clientTin,testType, catList, paList)
+saveTest()
-validateTest(t)
-addTest(t)
}
class TestTypeStore{
-array
-testType
+getByCode(testTypeCode)
}
class ParameterStore{
-array
-pc
+ParameterStore()
+getParameter(parameterCode)
+addParameter(parameter)
}
class CategoryStore{
-array
+getCategory(categoryCode)
+addCategory(category)
}
class TestTypeMapper{
+toDto(ttList)
-toDto(testType)
}
class TestTypeDTO{
-TestTypeID
-description
+getTestTypeID()
+getDescription()
}

class CategoryListMapper{
+toDTO(categoriesList)
-toDTO(category)
}
class CategoryDTO{
-code
-name
+getCode()
+getName()
}

class ParameterMapper{
+toDTO(parametersList)
-toDTO(parameter)
}
class ParameterDTO{
-code
-name
+getCode()
+getName()
}

class Company{
-designation
-parameterCategoryList
-clientList
-testList
-parameterList
-testTypeList
+getTestTypeList()
+categoryStore()
+parameterStore()
}
class RegisterTestController{
+getLists()
+existsClients(clientCC)
+getTestTypeList()
+getCategories(testTypeCode)
+getParameters(categoryCode)
+addParameter(parameterCode)
+createTest()
+saveTest()
}
class RegisterTestUI{
}

class TestType{
-testID
-description
-collectingMethod
-catStore
-externalModule
+getCategories()
}

class Test{
-testCode
-testNhsNumber
-clientTin
-testType
-catList
-paList
-createdDate
+Test(testNhsNumber,testCode,testType,catList,paList,ClientCc)
+addTestParameters()
-changeState(state)
}
class TestParameterStore{
-pCode
+TestParameterStore()
+createParameterTest(pCode)
+add()
}
class TestParameter{
-parameterCode
+TestParameter(parameterCode)
}

class Parameter{
-name
-code
-description
-cat
+getParameterCode()
}


RegisterTestUI ..> RegisterTestController
RegisterTestController ..>CategoryListMapper
RegisterTestController ..>TestTypeMapper
RegisterTestController ..>TestType
RegisterTestController ..>Company
RegisterTestController ..>ParameterStore
RegisterTestController ..>TestStore
RegisterTestController ..>CategoryStore
RegisterTestController ..>ParameterMapper
RegisterTestController ..>TestTypeStore
RegisterTestController ..>ClientStore

ParameterMapper ..> ParameterDTO
CategoryListMapper ..> CategoryDTO
TestTypeMapper ..> TestTypeDTO

Company "1" --> "1" TestTypeStore: adopts
Company "1" --> "1" ClientStore: adopts
Company "1" --> "1" ParameterStore: adopts
Company "1" --> "1" TestStore: adopts
Company "1" --> "1" CategoryStore: adopts

TestTypeStore "1" --> "*" TestType:stores
TestStore "1" --> "*" Test: stores
Test "1" --> "1" TestParameterStore
TestParameterStore "1" --> "*" TestParameter: stores
ParameterStore "1" --> "*" Parameter: stores
Test "1" --> "*" Parameter: has
@enduml