@startuml
autonumber

participant ":CreateTestController" as CTRL
participant ":Company" as C
participant ":ParameterMapper" as MAPPER
participant "listAllParameters: List<Parameters>" as AllP
participant "listParametersDto: List<ParametersDto>" as DTO
participant "objDto:ParameterDto" as OBJ

[o->CTRL:
activate CTRL
CTRL -> C: getListOfParameters()
activate C
C-->AllP**
rnote over C, AllP: loop to populate listAllParameters is ommited
C->CTRL: listAllParameters
deactivate C
CTRL->MAPPER: toDto(listAllParameters)
activate MAPPER
MAPPER->DTO**: create()

loop for each object of listAllParameters [i]
loop for each object of listCat [j]
alt getCategory[i]=listCat[j]
MAPPER->AllP: obj=get[i]
MAPPER->MAPPER:objDto=toDto(obj)
activate MAPPER
MAPPER-->OBJ**:create()
deactivate MAPPER
MAPPER->DTO:add(objDto)
activate DTO
deactivate DTO
end
end
end
MAPPER->CTRL: listParametersDto
deactivate MAPPER
[o<-CTRL
@enduml