@startuml
class Company{
Name
}
class Test{
Client;
Test ID;
Type of Test;
}
class TypeTest{
Test ID;
Collecting Method;
Parameter Categories;
}

class Receptionist{
}

class Parameter{
name;
code;
description;
}
class ParameterCategory{
name;
code;
}


Company "1" -- "*" Receptionist: employs >
Parameter "1" -- "1" ParameterCategory : has a >
Receptionist "1" -- "*" Test: register in application >
Test "1" -- "*" Parameter : has >
TypeTest "1" -- "*" Test : as a <
TypeTest "1" -- "*" ParameterCategory : has >

@enduml
@enduml