@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant "task:SendReportTask" as task
participant "linReg:LinearRegression" as linReg
participant "mlinReg:LinearRegression" as linReg
participant "tStore:TestStore" as tStore
participant "api:NHSApi" as api

[o-> task: run()
alt linear Regression
    task --> linReg** : creates()
    alt variable equal number of tests
    else variable equal age average
    end
else multilinear Regression
end
activate task
deactivate task
@enduml