@startuml

autonumber
participant "Time" as tm
participant "System" as sys

activate tm
loop every day at 6:00AM
    tm -> sys: create and send the report
    activate sys
    sys --> tm: informs the success into a log file
    deactivate
end
deactivate tm

@enduml