@startuml
'https://plantuml.com/sequence-diagram
autonumber
actor Receptionist as R
participant "System" as S
activate R
activate S
R -> S: wants to register a client in the system
S --> R: requests data (name, citizen card number, \nnational healthcare service number, birth date, sex,\n tax identification number, phone, e-mail)
R -> S: types requested data

deactivate S

@enduml