@startuml

class RegisterClientUI{
}

class RegisterClientController{
    + getRoleList()
    + getStore()
    + createClient(int cc, int nhs, string birthDate, string sex, int tinNumber, int phoneNumber, string email, string name)
    + saveClient()
    + addUserWithRole(string name, string email, string password)
}

class AuthFacade{
}

class UserSession{
}

class Company{
    + getRoleList()
    + getStore()
}

class Client{
    + createClient(int cc, int nhs, string birthDate, string sex, int tinNumber, int phoneNumber, string email, string name)
}

class ClientStore{
    + createClient(int cc, int nhs, string birthDate, string sex, int tinNumber, int phoneNumber, string email, string name)
    + saveClient()
    + validateClient()
    + existsUser(string email)
    + addUserWithRole(string name, string email, string password)
}

class RoleStore{
    + getRoleList()
}

RegisterClientUI ..> RegisterClientController
RegisterClientController ..> Company
RegisterClientController ..> ClientStore
ClientStore ..> Client
Company ..> ClientStore: creates
Company ..> RoleStore

@enduml