@startuml
autonumber

actor Receptionist as R
participant ":RegisterClientUI" as UI
participant ":RegisterClientController" as CTRL
participant ":AuthFacade" as Auth
participant ":UserSession" as User
participant ":Company" as COMPANY
participant "c: Client" as C


activate R
R -> UI: asks to register a new client
activate UI

R <- UI: requests new user's registering data (name, e-mail, password)
deactivate UI
R -> UI: types requested data
activate UI
UI -> CTRL : addUser(name, e-mail, password)
activate CTRL
CTRL -> Auth: addUser(name, e-mail, password)
deactivate CTRL

UI --> R: asks client's login information (e-mail, password)
deactivate UI
R -> UI: types information
activate UI

UI -> CTRL : doLogin(e-mail, password)
activate CTRL
CTRL -> Auth: doLogin(e-mail, password)
activate Auth
CTRL -> Auth: getCurrentSession()
deactivate Auth
CTRL -> User: UserSession(User user)
activate User
deactivate User
deactivate CTRL

deactivate CTRL
UI -> R: requests client's registration data (citizen card number, NHS number,\n birth date, sex, TIN number, phone number, e-mail, name)
deactivate UI
R -> UI: types data
activate UI
UI -> CTRL : CreateClient(citizen card number, NHS number, birth date, sex,\n TIN number, phone number, e-mail, name)
activate CTRL
CTRL -> COMPANY: CreateClient(citizen card number, NHS number, birth date, sex,\n TIN number, phone number, e-mail, name)
activate COMPANY

COMPANY -> C: c = Create(citizen card number, NHS number, birth date, sex,\n TIN number, phone number, e-mail, name)
deactivate COMPANY
deactivate CTRL
R <-- UI: shows data and requests confirmation
deactivate UI
R -> UI: confirms data
activate UI
UI-> CTRL : saveClient()
activate CTRL
CTRL -> COMPANY: saveClient(c)
activate COMPANY
COMPANY -> COMPANY : validateClient(c)
activate COMPANY
deactivate COMPANY
COMPANY -> COMPANY : saveClient(c)
activate COMPANY
deactivate COMPANY
deactivate COMPANY
deactivate CTRL

deactivate CTRL
UI -> CTRL: doLogout()
activate CTRL
CTRL -> Auth: doLogout()
deactivate CTRL
UI --> R : Informs operation success
deactivate CTRL
deactivate UI
deactivate R

@enduml