@startuml

class RegisterClientUI{
}

class RegisterClientController{
    + getStore()
    + createClient(int cc, int nhs, string birthDate, string sex, int tinNumber, int phoneNumber, string email, string name)
    + saveClient()
}

class AuthFacade{
    +addUserWithRole(name, email, password, roleId)
}


class Company{
    + getStore()
}

class Client{
    + Client(int cc, int nhs, string birthDate, string sex, int tinNumber, int phoneNumber, string email, string name)
    + getPassword()
}

class ClientStore{
    + createClient(int cc, int nhs, string birthDate, string sex, int tinNumber, int phoneNumber, string email, string name)
    + saveClient()
    + validateClient()
    + addUserWithRole(string name, string email, string roleId)
}


RegisterClientUI ..> RegisterClientController
RegisterClientController ..> Company
RegisterClientController ..> ClientStore
Company --> ClientStore

ClientStore --> Client
ClientStore ..> AuthFacade
@enduml